template: blockchain_startup
name: "DevOps Engineer – Blockchain/Web3"
headline_variant: blockchain
summary_key: blockchain_infrastructure
skill_categories:
  - cloud_platforms
  - kubernetes
  - cicd
  - monitoring
  - blockchain
skill_levels:
  - expert
  - proficient
filters:
  include_tags:
    - blockchain
    - web3
    - startup
    - high-scale
    - distributed-systems
  priority_tags:
    - blockchain
    - web3
    - distributed-systems
    - startup
    - high-scale
  exclude_tags:
    - fintech
    - legacy
  limit_years: 7
options:
  highlight_achievements: true
  max_experience_blocks: 5
