template: senior_devops_standard
name: "Senior DevOps Engineer – Enterprise"
headline_variant: senior
summary_key: senior_devops
skill_categories:
  - cloud_platforms
  - kubernetes
  - cicd
  - iac
  - monitoring
  - security
  - programming
  - databases
skill_levels:
  - expert
  - proficient
filters:
  priority_tags:
    - leadership
    - management
    - kubernetes
    - high-scale
    - ai
  exclude_tags:
    - legacy
    - early-career
  limit_years: 7
options:
  highlight_achievements: true
  emphasise_leadership: true
  max_experience_blocks: 5
